# Generated by Django 3.2.6 on 2022-01-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220102_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feautured_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
