# Generated by Django 3.2.6 on 2022-01-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_feautured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='feautured_image',
            new_name='featured_image',
        ),
    ]
